services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-trovian-java:latest
    container_name: api-trovian
    ports:
      - "127.0.0.1:${SERVER_PORT:-8081}:8081"
    env_file:
      - docker.env
    networks:
      - trovian-network
    restart: unless-stopped

    depends_on:
      mongodb:
        condition: service_healthy
      activemq:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/api/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 5

networks:
  trovian-network:
    external: true
