version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: trovian-postgres
    environment:
      POSTGRES_DB: troviandb
      POSTGRES_USER: trovian
      POSTGRES_PASSWORD: trovian123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trovian-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trovian"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ActiveMQ
  activemq:
    image: apache/activemq-classic:latest
    container_name: trovian-activemq
    ports:
      - "61616:61616"  # JMS
      - "8161:8161"    # Web Console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - trovian-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8161 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  trovian-network:
    driver: bridge
