version: '3.8'

services:
  api:
    build: .
    container_name: api-trovian
    ports:
      - "127.0.0.1:${SERVER_PORT:-8081}:8081"
    env_file:
      - docker.env
    networks:
      - trovian-network
    restart: unless-stopped

networks:
  trovian-network:
    driver: bridge
