--liquibase formatted sql

-- =====================================================================
-- P0-A | Tipos inteiros e chaves estrangeiras
--
-- Corrige PKs serial4 que estouram e colunas int4 que apontam para
-- id int8, o que hoje impede a criacao de FK.
--
-- NAO trata transmissao, transmissao_basica e telemetria: essas tres
-- sao recriadas do zero no P0-C, ja com bigint.
-- =====================================================================


-- changeset trovian:p0a-01-hodometro-id-bigint
-- comment: hodometro.id era serial4. Teto de 2,1 bi e alcancavel em tabela alimentada por telemetria.
ALTER TABLE public.hodometro ALTER COLUMN id TYPE bigint;
ALTER SEQUENCE public.hodometro_id_seq AS bigint;
-- rollback ALTER SEQUENCE public.hodometro_id_seq AS integer;
-- rollback ALTER TABLE public.hodometro ALTER COLUMN id TYPE integer;


-- changeset trovian:p0a-02-hodometro-fk-duplicada
-- comment: fk_hodometro_veiculo e hodometro_veiculo_fk sao identicas. Toda insercao validava duas vezes.
ALTER TABLE public.hodometro DROP CONSTRAINT IF EXISTS fk_hodometro_veiculo;
-- rollback ALTER TABLE public.hodometro ADD CONSTRAINT fk_hodometro_veiculo FOREIGN KEY (veiculo) REFERENCES public.veiculo(id);


-- changeset trovian:p0a-03-hodometro-motorista
-- comment: id_motorista era int4 contra motorista.id int8, por isso nao havia FK.
ALTER TABLE public.hodometro ALTER COLUMN id_motorista TYPE bigint;
ALTER TABLE public.hodometro ALTER COLUMN id_transmissao TYPE bigint;

ALTER TABLE public.hodometro
    ADD CONSTRAINT fk_hodometro_motorista
    FOREIGN KEY (id_motorista) REFERENCES public.motorista(id);
-- rollback ALTER TABLE public.hodometro DROP CONSTRAINT fk_hodometro_motorista;
-- rollback ALTER TABLE public.hodometro ALTER COLUMN id_transmissao TYPE integer;
-- rollback ALTER TABLE public.hodometro ALTER COLUMN id_motorista TYPE integer;


-- changeset trovian:p0a-04-hodometro-denormalizacao
-- comment: nome_motorista denormalizado ao lado do id. O nome pode mudar e a evidencia fica fragil.
ALTER TABLE public.hodometro DROP COLUMN IF EXISTS nome_motorista;
-- rollback ALTER TABLE public.hodometro ADD COLUMN nome_motorista text;


-- changeset trovian:p0a-05-comando-id
-- comment: comando.id era int4 sem default nem sequencia. A aplicacao gerava o id, o que quebra sob concorrencia.
ALTER TABLE public.comando ALTER COLUMN id TYPE bigint;
ALTER TABLE public.comando ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.comando ALTER COLUMN cliente TYPE bigint;
ALTER TABLE public.comando ALTER COLUMN id_comando_referente TYPE bigint;

ALTER TABLE public.comando
    ADD CONSTRAINT fk_comando_cliente
    FOREIGN KEY (cliente) REFERENCES public.cliente(id);
-- rollback ALTER TABLE public.comando DROP CONSTRAINT fk_comando_cliente;
-- rollback ALTER TABLE public.comando ALTER COLUMN id_comando_referente TYPE integer;
-- rollback ALTER TABLE public.comando ALTER COLUMN cliente TYPE integer;
-- rollback ALTER TABLE public.comando ALTER COLUMN id DROP IDENTITY;
-- rollback ALTER TABLE public.comando ALTER COLUMN id TYPE integer;


-- changeset trovian:p0a-06-tabelas-sem-pk
-- comment: sem PK nao ha replicacao logica, nao ha REPLICA IDENTITY e o ORM se comporta de forma imprevisivel.
ALTER TABLE public.usuario_roles
    ADD CONSTRAINT usuario_roles_pkey PRIMARY KEY (usuario_id, role);

ALTER TABLE public.modelo_checklist_veiculo
    ADD CONSTRAINT modelo_checklist_veiculo_pkey
    PRIMARY KEY (modelo_checklist_id, veiculo_id);

ALTER TABLE public.config_notificacao_destinatarios
    ADD CONSTRAINT config_notif_dest_pkey PRIMARY KEY (config_id, usuario_id);

ALTER TABLE public.config_notificacao_dias_antecedencia
    ADD CONSTRAINT config_notif_dias_pkey PRIMARY KEY (config_id, dias);
-- rollback ALTER TABLE public.config_notificacao_dias_antecedencia DROP CONSTRAINT config_notif_dias_pkey;
-- rollback ALTER TABLE public.config_notificacao_destinatarios DROP CONSTRAINT config_notif_dest_pkey;
-- rollback ALTER TABLE public.modelo_checklist_veiculo DROP CONSTRAINT modelo_checklist_veiculo_pkey;
-- rollback ALTER TABLE public.usuario_roles DROP CONSTRAINT usuario_roles_pkey;

-- NOTA: usuario_roles.role e config_*.usuario_id/dias sao NULLABLE hoje.
-- PK exige NOT NULL, entao o ALTER acima falha se houver nulo.
-- Com a base vazia isso nao ocorre. Os NOT NULL vao no changeset seguinte.


-- changeset trovian:p0a-07-not-null-chaves
ALTER TABLE public.usuario_roles ALTER COLUMN role SET NOT NULL;
ALTER TABLE public.config_notificacao_destinatarios ALTER COLUMN usuario_id SET NOT NULL;
ALTER TABLE public.config_notificacao_dias_antecedencia ALTER COLUMN dias SET NOT NULL;
-- rollback ALTER TABLE public.config_notificacao_dias_antecedencia ALTER COLUMN dias DROP NOT NULL;
-- rollback ALTER TABLE public.config_notificacao_destinatarios ALTER COLUMN usuario_id DROP NOT NULL;
-- rollback ALTER TABLE public.usuario_roles ALTER COLUMN role DROP NOT NULL;


-- changeset trovian:p0a-08-unicidade-multitenant
-- comment: unique global em peca.codigo e fornecedor.cnpj_cpf impedia dois clientes de cadastrar a mesma peca ou o mesmo posto.
ALTER TABLE public.peca       DROP CONSTRAINT IF EXISTS uk_skx3p18h2aegobmgv0cpaeex5;
ALTER TABLE public.fornecedor DROP CONSTRAINT IF EXISTS uk_p74lwinn8v0p251uh04910xm9;

ALTER TABLE public.fornecedor
    ADD CONSTRAINT uq_fornecedor_doc_cliente UNIQUE (cliente_id, cnpj_cpf);
-- rollback ALTER TABLE public.fornecedor DROP CONSTRAINT uq_fornecedor_doc_cliente;
-- rollback ALTER TABLE public.fornecedor ADD CONSTRAINT uk_p74lwinn8v0p251uh04910xm9 UNIQUE (cnpj_cpf);
-- rollback ALTER TABLE public.peca ADD CONSTRAINT uk_skx3p18h2aegobmgv0cpaeex5 UNIQUE (codigo);


-- changeset trovian:p0a-09-motorista-cpf
-- comment: CPF sem unicidade permitia motorista duplicado, o que quebra qualquer regra de comportamento.
CREATE UNIQUE INDEX uq_motorista_cpf_cliente
    ON public.motorista (cliente_id, cpf)
    WHERE status = true;
-- rollback DROP INDEX public.uq_motorista_cpf_cliente;
