package com.trovian.enums;

public enum PosicaoPneu {
    DIANTEIRO_ESQUERDO,
    DIANTEIRO_DIREITO,
    TRASEIRO_ESQUERDO_INTERNO,
    TRASEIRO_ESQUERDO_EXTERNO,
    TRASEIRO_DIREITO_INTERNO,
    TRASEIRO_DIREITO_EXTERNO,
    ESTEPE_1,
    ESTEPE_2,
    ESTEPE_3
}
