--liquibase formatted sql

-- =====================================================================
-- P0-C | Particionamento das tabelas de telemetria
--
-- POR QUE AGORA: 100 veiculos transmitindo a cada 60s geram ~4,3 milhoes
-- de linhas por mes, POR TABELA. Sao tres tabelas. Sem particao:
--   - DELETE de expurgo trava a tabela por horas
--   - autovacuum nao acompanha e o bloat cresce sem limite
--   - o indice deixa de caber em memoria
--   - consulta por periodo varre tudo
--
-- Converter tabela comum em particionada com volume = copiar tudo.
-- Com a base vazia, este changeset roda em segundos. Este e o item de
-- maior prazo de validade de toda a Fase P0.
--
-- ESTRATEGIA: como a base esta vazia, recriamos as tres tabelas ja
-- particionadas, com bigint e timestamptz de origem. Nao ha migracao
-- de dados. POR ISSO ESTE CHANGESET DESTROI DADOS: so aplique enquanto
-- a base for de teste.
--
-- A chave de particao precisa fazer parte da PK, entao a PK vira
-- composta (id, data). Consequencia: nao e possivel criar FK apontando
-- para o id dessas tabelas. Nenhuma existia, e as referencias logicas
-- (hodometro.id_transmissao) continuam como estao.
-- =====================================================================


-- changeset trovian:p0c-01-drop-telemetria-antiga
-- preconditions onFail:HALT
-- precondition-sql-check expectedResult:0 SELECT count(*) FROM public.transmissao
-- comment: guarda de seguranca. Se houver qualquer linha em transmissao, o changeset para.
DROP TABLE IF EXISTS public.transmissao        CASCADE;
DROP TABLE IF EXISTS public.transmissao_basica CASCADE;
DROP TABLE IF EXISTS public.telemetria         CASCADE;
-- rollback SELECT 'estruturas antigas nao sao restauraveis; use backup' AS aviso;


-- changeset trovian:p0c-02-transmissao-particionada
CREATE TABLE public.transmissao (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY,
    data_transmissao                timestamptz NOT NULL,
    veiculo                         bigint      NOT NULL,
    cliente_id                      bigint      NOT NULL,

    -- posicao
    latitude                        float8      NOT NULL,
    longitude                       float8      NOT NULL,
    altitude                        int4,
    direcao                         int4,
    velocidade                      float8,
    velocidade_gps                  float8,
    endereco                        varchar(255),
    nome_local                      text,

    -- medidores: fonte primaria do antifraude
    hodometro                       float8,
    horimetro                       float8,
    distancia_percorrida            float8,
    distancia                       float8,

    -- estado do veiculo
    ignicao_ativa                   int2,
    rpm_corrente                    float8,
    temperatura                     float8,
    voltagem                        float8,
    percentual_bateria_equipamento  int4,

    -- identificacao do condutor: resolve MOTORISTA_DIVERGE_IBUTTON
    ibutton                         varchar(255),
    ibutton_manual                  bool,
    motorista_id                    bigint,

    -- eventos e alarmes
    alerta                          bool,
    evento                          bool,
    tipo_alerta                     int4,
    tipo_evento                     int4,
    identificador_de_evento         int4,
    panico                          int2,
    panico_visualizado              int2,
    panico_desativado               int2,
    execesso_velocidade             int2,
    jamming                         int2,
    sinal_jamming                   varchar(255),
    falha_alimentacao_externa       int2,
    ponto_de_referencia             int2,
    viagem                          bool,

    -- entradas e saidas digitais
    entrada_digital_um              bool,
    entrada_digital_dois            bool,
    entrada_digital_tres            bool,
    entrada_digital_quatro          bool,
    saida4                          int2,

    -- comunicacao
    gps_ativo                       int2,
    gprs_ativo                      int2,
    conexao_primaria_ativa          int2,
    data_gps                        timestamptz,
    data_servidor                   timestamptz,
    data_envio_sms                  timestamptz,
    ultimo_envio_sms                bool,
    sequencia_rastreador            int4,
    tipo_rastreador                 varchar(10),
    tipo_transmissao                varchar(30),
    rastreador                      text,
    equipamento_portatil            int4,
    modo                            int4,
    observacao                      text,
    dados_puro_rastreador           text,

    CONSTRAINT transmissao_pk PRIMARY KEY (id, data_transmissao)
) PARTITION BY RANGE (data_transmissao);
-- rollback DROP TABLE public.transmissao;


-- changeset trovian:p0c-03-transmissao-basica-particionada
CREATE TABLE public.transmissao_basica (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY,
    data_transmissao                timestamptz NOT NULL,
    veiculo                         bigint      NOT NULL,
    cliente_id                      bigint      NOT NULL,
    latitude                        float8,
    longitude                       float8,
    altitude                        int4,
    direcao                         int4,
    velocidade                      float8,
    hodometro                       float8,
    horimetro                       float8,
    distancia_percorrida            float8,
    ignicao_ativa                   int2,
    rpm_corrente                    float8,
    temperatura                     float8,
    voltagem                        float8,
    percentual_bateria_equipamento  int4,
    ibutton                         varchar(255),
    motorista_id                    bigint,
    alerta                          bool,
    evento                          bool,
    tipo_alerta                     int4,
    tipo_evento                     int4,
    identificador_de_evento         int4,
    panico                          int2,
    panico_visualizado              int2,
    panico_desativado               int2,
    execesso_velocidade             int2,
    jamming                         int2,
    sinal_jamming                   varchar(255),
    falha_alimentacao_externa       int2,
    ponto_de_referencia             int2,
    veiculo_fora_ancora             int2,
    viagem                          bool,
    entrada_digital_um              bool,
    entrada_digital_dois            bool,
    gps_ativo                       int2,
    gprs_ativo                      int2,
    conexao_primaria_ativa          int2,
    saida4                          int2,
    data_registro                   timestamptz,
    data_envio_sms                  timestamptz,
    ultimo_envio_sms                bool,
    id_transmissao_pai              bigint,
    endereco                        varchar(255),
    bairro                          varchar(255),
    cidade                          varchar(255),
    estado                          varchar(255),
    equipamento_portatil            int4,
    modo                            int4,

    CONSTRAINT transmissao_basica_pk PRIMARY KEY (id, data_transmissao)
) PARTITION BY RANGE (data_transmissao);
-- rollback DROP TABLE public.transmissao_basica;


-- changeset trovian:p0c-04-telemetria-particionada
-- comment: esta e a tabela mais valiosa do antifraude. fuel_level e combustivel_total_usado_pelo_motor permitem verificacao FISICA do abastecimento.
CREATE TABLE public.telemetria (
    id                                      bigint GENERATED BY DEFAULT AS IDENTITY,
    data_cadastro                           timestamptz NOT NULL,
    veiculo                                 bigint      NOT NULL,
    cliente_id                              bigint      NOT NULL,
    id_transmissao                          bigint,

    -- *** COMBUSTIVEL: nucleo do antifraude ***
    -- fuel_level: nivel do tanque em %. Comparado antes/depois do
    -- abastecimento, mostra quantos litros REALMENTE entraram.
    -- Precisao de 5 a 10% (balanco do liquido, inclinacao, sensor
    -- nao linear). Serve para pegar divergencia grosseira.
    fuel_level                              int4,
    -- acumulado de combustivel queimado pela ECU, em litros.
    -- Precisao de 2 a 3%. Base de CONSUMO_ATIPICO_ECU, melhor que
    -- o metodo tanque-a-tanque.
    combustivel_total_usado_pelo_motor      float8,
    taxa_combustivel                        int4,
    economia_combustivel_instantanea        int4,

    -- medidores CAN
    total_odometer                          float8,
    trip_odometer                           float8,
    total_horas_operacao_motor              int4,

    -- motor
    rpm                                     int4,
    temperatura_motor                       int4,
    temperatura_liquido_arrefecimento_motor int4,
    carga_atual_do_motor                    int4,
    posicao_do_pedal_de_acelaracao          int4,
    velocidade_baseada_na_roda              int4,
    interruptor_de_freio                    int4,
    chave_de_embreagem                      int4,
    controle_de_cruzeiro_ativo              int4,
    estado_pto                              int4,

    -- direcao defensiva
    acelaracao_brusca                       bool,
    freada_brusca                           bool,
    curva_brusca                            bool,
    green_driving_value                     int4,
    axix_x                                  int4,
    axix_y                                  int4,
    axix_z                                  int4,

    processado                              bool DEFAULT false,
    data_processamento                      timestamptz,

    CONSTRAINT telemetria_pk PRIMARY KEY (id, data_cadastro)
) PARTITION BY RANGE (data_cadastro);
-- rollback DROP TABLE public.telemetria;


-- changeset trovian:p0c-05-indices
-- comment: transmissao nao tinha indice por veiculo. A consulta central do antifraude ("posicao e hodometro deste veiculo neste instante") era seq scan.
CREATE INDEX idx_transmissao_veiculo_data
    ON public.transmissao (veiculo, data_transmissao DESC);
CREATE INDEX idx_transmissao_cliente_data
    ON public.transmissao (cliente_id, data_transmissao DESC);
CREATE INDEX idx_transmissao_hodometro
    ON public.transmissao (veiculo, data_transmissao DESC)
    WHERE hodometro IS NOT NULL;
CREATE INDEX idx_transmissao_ibutton
    ON public.transmissao (ibutton, data_transmissao DESC)
    WHERE ibutton IS NOT NULL;

CREATE INDEX idx_transmissao_basica_veiculo_data
    ON public.transmissao_basica (veiculo, data_transmissao DESC);

CREATE INDEX idx_telemetria_veiculo_data
    ON public.telemetria (veiculo, data_cadastro DESC);
-- indice dedicado a verificacao fisica do abastecimento
CREATE INDEX idx_telemetria_combustivel
    ON public.telemetria (veiculo, data_cadastro DESC)
    WHERE fuel_level IS NOT NULL;
CREATE INDEX idx_telemetria_nao_processado
    ON public.telemetria (data_cadastro)
    WHERE processado = false;
-- rollback SELECT 1;


-- changeset trovian:p0c-06-fks
ALTER TABLE public.transmissao
    ADD CONSTRAINT fk_transmissao_veiculo   FOREIGN KEY (veiculo)    REFERENCES public.veiculo(id),
    ADD CONSTRAINT fk_transmissao_cliente   FOREIGN KEY (cliente_id) REFERENCES public.cliente(id),
    ADD CONSTRAINT fk_transmissao_motorista FOREIGN KEY (motorista_id) REFERENCES public.motorista(id);

ALTER TABLE public.transmissao_basica
    ADD CONSTRAINT fk_transmissao_basica_veiculo FOREIGN KEY (veiculo)    REFERENCES public.veiculo(id),
    ADD CONSTRAINT fk_transmissao_basica_cliente FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);

ALTER TABLE public.telemetria
    ADD CONSTRAINT fk_telemetria_veiculo FOREIGN KEY (veiculo)    REFERENCES public.veiculo(id),
    ADD CONSTRAINT fk_telemetria_cliente FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);
-- rollback SELECT 1;


-- =====================================================================
-- GESTAO DE PARTICOES
-- =====================================================================

-- changeset trovian:p0c-07-funcao-criar-particoes splitStatements:false
-- comment: cria particoes mensais adiantadas. Sem particao para a data, o INSERT falha.
CREATE OR REPLACE FUNCTION public.criar_particoes_mensais(
    p_meses_futuros int DEFAULT 3
) RETURNS int
LANGUAGE plpgsql AS $$
DECLARE
    tabelas  constant text[] := ARRAY['transmissao','transmissao_basica','telemetria'];
    t        text;
    i        int;
    inicio   date;
    fim      date;
    nome     text;
    criadas  int := 0;
BEGIN
    FOREACH t IN ARRAY tabelas LOOP
        FOR i IN 0 .. p_meses_futuros LOOP
            inicio := date_trunc('month', current_date)::date + (i || ' month')::interval;
            fim    := (inicio + interval '1 month')::date;
            nome   := format('%s_p%s', t, to_char(inicio, 'YYYYMM'));

            IF to_regclass('public.' || nome) IS NULL THEN
                EXECUTE format(
                    'CREATE TABLE public.%I PARTITION OF public.%I FOR VALUES FROM (%L) TO (%L)',
                    nome, t, inicio, fim
                );
                criadas := criadas + 1;
                RAISE NOTICE 'particao criada: %', nome;
            END IF;
        END LOOP;
    END LOOP;
    RETURN criadas;
END $$;

COMMENT ON FUNCTION public.criar_particoes_mensais IS
    'Cria particoes mensais adiantadas. Agendar diariamente. Sem particao para a data, o INSERT falha.';
-- rollback DROP FUNCTION public.criar_particoes_mensais(int);


-- changeset trovian:p0c-08-funcao-expurgo splitStatements:false
-- comment: expurgo por DROP PARTITION e instantaneo. Um DELETE equivalente levaria horas e deixaria bloat.
CREATE OR REPLACE FUNCTION public.expurgar_particoes_antigas(
    p_meses_retencao int DEFAULT 24,
    p_dry_run        boolean DEFAULT true
) RETURNS TABLE (particao text, acao text)
LANGUAGE plpgsql AS $$
DECLARE
    corte date := (date_trunc('month', current_date) - (p_meses_retencao || ' month')::interval)::date;
    r     record;
BEGIN
    FOR r IN
        SELECT c.relname
        FROM   pg_class c
        JOIN   pg_inherits i ON i.inhrelid = c.oid
        JOIN   pg_class p    ON p.oid = i.inhparent
        WHERE  p.relname IN ('transmissao','transmissao_basica','telemetria')
          AND  c.relname ~ '_p[0-9]{6}$'
          AND  to_date(right(c.relname, 6), 'YYYYMM') < corte
        ORDER BY c.relname
    LOOP
        IF p_dry_run THEN
            particao := r.relname; acao := 'SERIA REMOVIDA'; RETURN NEXT;
        ELSE
            EXECUTE format('DROP TABLE public.%I', r.relname);
            particao := r.relname; acao := 'REMOVIDA'; RETURN NEXT;
        END IF;
    END LOOP;
END $$;

COMMENT ON FUNCTION public.expurgar_particoes_antigas IS
    'Expurgo por DROP de particao. Padrao dry_run=true. Ajuste a retencao a politica de LGPD do cliente.';
-- rollback DROP FUNCTION public.expurgar_particoes_antigas(int, boolean);


-- changeset trovian:p0c-09-particoes-iniciais
-- comment: cria o mes corrente mais 6 a frente. Sem isto, o primeiro INSERT falha.
SELECT public.criar_particoes_mensais(6);
-- rollback SELECT 1;


-- =====================================================================
-- AGENDAMENTO OBRIGATORIO
--
-- criar_particoes_mensais NAO roda sozinha. Se ninguem chamar, a
-- telemetria para de ser aceita quando o ultimo mes criado terminar.
-- Este e o unico ponto de falha operacional introduzido aqui.
--
-- Opcao A, pg_cron dentro do banco:
--   CREATE EXTENSION IF NOT EXISTS pg_cron;
--   SELECT cron.schedule('particoes-trovian', '0 3 * * *',
--                        'SELECT public.criar_particoes_mensais(3)');
--
-- Opcao B, @Scheduled no Spring (sem extensao nova):
--   @Scheduled(cron = "0 0 3 * * *")
--   public void criarParticoes() {
--       jdbc.queryForObject("SELECT public.criar_particoes_mensais(3)", Integer.class);
--   }
--
-- Adicione alerta se criar_particoes_mensais falhar. Particao faltando
-- derruba a ingestao de telemetria inteira.
-- =====================================================================
